esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

esp32_improv:
  authorizer: none

esp32_ble:
  enable_on_boot: false

esphome:
  on_boot:
    priority: -100
    then:
      - if:
          condition:
            lambda: 'return !wifi::global_wifi_component->has_sta();'
          then:
            - logger.log: "No WiFi credentials configured, enabling BLE for Improv setup"
            - ble.enable

wifi:
  on_connect:
    - delay: 15s
    - if:
        condition:
          ble.enabled:
        then:
          - esp32_ble_tracker.stop_scan:
          - delay: 5s
          - ble.disable
          - delay: 5s
    - ble.enable
    - delay: 5s
    - esp32_ble_tracker.start_scan:
        continuous: true
